CREATE TABLE IF NOT EXISTS sessions (
    session_id TEXT PRIMARY KEY,
    context JSON,
    history JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);